### ISSUE TITLE
App is not compiling

### ISSUE THREAD

**Issue by OSKUDA** [sahnavin123/bmi#1]
1.  Check for SDK version mismatch
2. Null safety checks
3. Logic checks
4. Business logic and UI integration checks

**Comment by sahnavin123** [comment]
we have to add ?? mark when we are using with nullable variable
i just found it todai
just remove ! and declare ?? whenever there can be null value

**Comment by OSKUDA** [comment]
This won't be a clean solution although it does the job.

Always try to reduse the use of nullable variable in your code.

`------
class CalculatorBrain {
  CalculatorBrain({required this.height, required this.weight});

  final int height;
  final int weight;

  late double _bmi;

  String calculateBMI() {
    _bmi = weight / pow(height / 100, 2);

    return _bmi.toStringAsFixed(1);
  }
-------`

We can reduce nullable variable by either making it **required** in the constructor, or declaring it as **late**

This is much clean and easier to read. Fits our purpose.
